# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b4ef2b31846372b2e1458fe3c1a86122776035dd8733ed667ed94ad27f0e89f8e4c3cd81b95ee49d6e1078cdaa9913f4dc5a2b787842cd2edba1f9deabcda3

test:
  secret_key_base: 86888a7a6e80793bd27cc2054812f962da76d5b492afecd6d3149040f4983cea891e96e18281e7b7c31e1c60ade777cef59f897f1d7741cf5b1af9dfe97818ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
